feat(training): adds single node ddp support
ZettaAI/zetta_utils pull request #387
Opened 2023-05-02 20:51 UTC by akhileshh

2023-05-02 23:28 UTC, supersergiy requested changes

2023-05-02 23:28 UTC, supersergiy commented on zetta_utils/layer/volumetric/tensorstore/backend.py
> +        },
I don't think we need this anymore

2023-05-02 23:28 UTC, supersergiy commented on zetta_utils/training/lightning/regimes/alignment/encoding_coarsener.py
> +        data_in = data_in.to(device)
PL is supposed to handle this, right?
Is there no other solution? It's counterintuitive for `validation_step` and `training_step` to have to differ in code this way.

2023-05-02 23:28 UTC, supersergiy commented on zetta_utils/training/lightning/trainers/default.py
> +    @pl.utilities.distributed.rank_zero_only
Shall we up the PL to 2.0?

2023-05-02 23:28 UTC, supersergiy commented on specs/akhilesh/encoding_coarsener_ddp_x0.cue
> +		"@type":					"pl.DDPStrategy"
Should we set the default strategy to this so that the user doesn't have to worry? Sounds like we won't need another strategy as of now

2023-05-02 23:28 UTC, supersergiy commented on specs/akhilesh/encoding_coarsener_ddp_x0.cue
Can we put this config into `specs/examples` as an example of DDP?

2023-05-04 17:53 UTC, supersergiy requested changes

2023-05-04 18:31 UTC, akhileshh commented on zetta_utils/training/lightning/trainers/default.py
> +    @pl.utilities.rank_zero.rank_zero_only
`@pl.utilities.rank_zero.rank_zero_only` is available on [1.7.7](https://github.com/Lightning-AI/lightning/blob/1.7.7/src/pytorch_lightning/utilities/rank_zero.py#L26)

2023-05-04 18:36 UTC, supersergiy approved these changes

2023-05-04 18:36 UTC, merged