Rounding Issues... Round 2
ZettaAI/zetta_utils pull request #466
Opened 2023-08-08 18:28 UTC by nkemnitz

2023-08-08 22:03 UTC, dodamih requested changes

2023-08-08 22:03 UTC, dodamih commented on zetta_utils/geometry/bbox_strider.py
Not sure if we want to use Vec3D for non-number types. Also, can we use a variable instead of using hardcoding 10?

2023-08-08 22:03 UTC, dodamih commented on zetta_utils/geometry/vec.py
Same thing about Vec3D[bool].

2023-08-08 22:17 UTC, nkemnitz commented on zetta_utils/geometry/bbox_strider.py
Sorry, which line / non-number type is this referring to?

2023-08-08 22:28 UTC, supersergiy commented on zetta_utils/geometry/bbox_strider.py
I think @dodamih is worried about using `Vec3D[bool]` on lines 52, 53 etc

We're dynamically looking into the types to return a correct one after many [[arithmetic operations](https://github.com/ZettaAI/zetta_utils/blob/5514fea68ceb24d6e48c2bb212611ac18e6ae5ae/zetta_utils/geometry/vec.py#L187-L190)], and it's not covered in any of the tests. 

Not sure if we want to extend Vec3D to correctly do arithmetic with `bool`'s, or just throw an exception there.

2023-08-09 19:10 UTC, dodamih commented on zetta_utils/geometry/bbox_strider.py
I'd push for exceptions - for one thing, `bool`s are not an Abelian group. There's also the added complexity from having to type infer correctly with bools, and the worry is that a user would see this and say "oh, this Vec3D container must support non-number types too".

2023-08-09 20:27 UTC, nkemnitz commented
Removed all traces of `Vec3D[bool]` and unified the precision related rounding calls to use a single constant `VEC3D_PRECISION`

2023-08-10 21:35 UTC, supersergiy approved these changes

2023-08-10 22:03 UTC, dodamih approved these changes

2023-08-11 03:21 UTC, merged