chore: pytorch-lightning upgrade
ZettaAI/zetta_utils pull request #526
Opened 2023-10-18 10:53 UTC by nkemnitz

2023-10-18 11:58 UTC, nkemnitz commented
I just checked the current main branch and noticed that it didn't export jit or onnx, either.

Think it's [this line](https://github.com/ZettaAI/zetta_utils/pull/526/files#diff-d7d24b371be4f087d00da084cea4983bbfe8e1d72f12ea6e737c6233d8cae702L232), which checked for `self.trainer.trace_configuration is None`, even though it's initialized and reset to `{}`? @dodamih , do you know what's going on here?

2023-10-18 15:28 UTC, supersergiy reviewed
I think multiprocessing was added for JIT tracing because of a memory leak in pytorch. @dodamih could you confirm?

2023-10-18 19:42 UTC, dodamih commented
@nkemnitz Oh, that does look like a bug. And yeah, we did add multiprocessing for JIT tracing due to a memory leak - the only way we could do it was to insulate it as an outside process.

2023-10-18 19:46 UTC, dodamih approved these changes

2023-10-18 20:30 UTC, supersergiy requested changes
Let's not merge until the leak is addressed

2023-10-20 19:35 UTC, nkemnitz commented
@supersergiy Took a while, but I think I got it now.
* `wandb` log operations are now only called from the PL `Trainers` - also modified the regimes accordingly
* source code is now also only logged once - by the rank=0 logger
* torch.jit and onnx export are now functional again (not working on `main`)
* added comment about the memory leak with consecutive jit.traces
* had to pin PL to 2.0.x - with 2.1.0 and multiple data loaders.I am getting segmentation faults after the first validation epoch

Successfully ran single node, multi-GPU training and 8 data loaders for multiple training epochs
Successfully ran multi node, single-GPU training with "0" data loaders. Multiple data loaders still won't work, but that's not because of the PL update.

"Successfully" here just means, it didn't crash and the graphs looked plausible... Some logging details might still be off, such as which workers are logging images.

2023-10-20 19:44 UTC, supersergiy approved these changes
💯

2023-10-20 19:44 UTC, merged